@startuml

title __BACKEND's Class Diagram__\n

  namespace inf112.skeleton.app {
    namespace ui.chat {
      namespace backend {
        class inf112.skeleton.app.ui.chat.backend.ChatFormatter {
            + allMessages : List<HashMap<String, String>>
            + chatters : HashMap<Integer, String>
            + messages : HashMap<String, String>
            + formatMessagesToDisplay()
            + getNamesWithMessages()
        }
      }
    }
  }
  

  namespace inf112.skeleton.app {
    namespace ui.chat {
      namespace backend {
        class inf112.skeleton.app.ui.chat.backend.ChatterData {
            + chatterID : int
            + name : String
            + ChatterData()
            + setData()
        }
      }
    }
  }
  

  namespace inf112.skeleton.app {
    namespace ui.chat {
      namespace backend {
        class inf112.skeleton.app.ui.chat.backend.Message {
            + message : String
            + messageID : int
            + Message()
            + Message()
            + assignID()
        }
      }
    }
  }
  

  namespace inf112.skeleton.app {
    namespace ui.chat {
      namespace backend {
        class inf112.skeleton.app.ui.chat.backend.Uwufier {
            + postUwudMessages : List<Message>
            + preUwudMessages : List<Message>
            - emojiis : String[]
            + Uwufier()
            + uwufyString()
        }
      }
    }
  }
  

  inf112.skeleton.app.ui.chat.backend.Message o-- inf112.skeleton.app.ui.chat.backend.ChatterData : sender


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
