@startuml

title __LIBGDX's Class Diagram__\n

  namespace inf112.skeleton.app {
    namespace libgdx {
      class inf112.skeleton.app.libgdx.Game {
          {static} + BOARD_X : int
          {static} + BOARD_Y : int
          + flagPositions : List<Flag>
          - batch : SpriteBatch
          - font : BitmapFont
          - playerLayer : TiledMapTileLayer
          - playerNormal : Cell
          - playerWon : Cell
          - renderer : OrthogonalTiledMapRenderer
          - tiledMap : TiledMap
          + create()
          + dispose()
          + keyUp()
          + loadMapLayers()
          + loadPlayerTextures()
          + loadTileMapFromFile()
          + pause()
          + render()
          + resize()
          + resume()
          + startGame()
          + translatePlayerLayer()
          + updateMap()
          - drawDeck()
          - getFlagPositionsFromLayer()
          - initializeRendering()
          - pickCardsOnKeyPress()
          - resetCellRotation()
          - rotateCellsAccordingToDirection()
          - startClient()
          - startHost()
      }
    }
  }
  

  namespace inf112.skeleton.app {
    namespace libgdx {
      class inf112.skeleton.app.libgdx.Map {
          + flagList : List<Flag>
          + playerLayer : PlayerRenderInformation[][]
          - BOARD_X : int
          - BOARD_Y : int
          - ID : int
          + Map()
          + clearPlayerLayer()
          + hasWon()
          + loadPlayers()
          + registerFlags()
          + setID()
      }
    }
  }
  

  namespace inf112.skeleton.app {
    namespace libgdx {
      class inf112.skeleton.app.libgdx.Map.PlayerRenderInformation {
          + PlayerRenderInformation()
      }
    }
  }
  

  namespace inf112.skeleton.app {
    namespace libgdx {
      class inf112.skeleton.app.libgdx.NetworkDataWrapper {
          + PlayerTokens : List<PlayerToken>
      }
    }
  }
  

  inf112.skeleton.app.libgdx.Game .up.|> com.badlogic.gdx.ApplicationListener
  inf112.skeleton.app.libgdx.Game -up-|> com.badlogic.gdx.InputAdapter
  inf112.skeleton.app.libgdx.Game o-- inf112.skeleton.app.game.GamePlayer : gamePlayer
  inf112.skeleton.app.libgdx.Game o-- inf112.skeleton.app.libgdx.Map : mlp
  inf112.skeleton.app.libgdx.Game o-- inf112.skeleton.app.network.Network : network
  inf112.skeleton.app.libgdx.Map +-down- inf112.skeleton.app.libgdx.Map.PlayerRenderInformation
  inf112.skeleton.app.libgdx.Map.PlayerRenderInformation o-- inf112.skeleton.app.game.objects.PlayerToken.Direction : dir
  inf112.skeleton.app.libgdx.Map.PlayerRenderInformation o-- inf112.skeleton.app.game.objects.PlayerToken.CHARACTER_STATES : state


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
