@startuml

title __NETWORK's Class Diagram__\n

  namespace inf112.skeleton.app {
    namespace network {
      class inf112.skeleton.app.network.CardList {
          + cardList : List<Card>
      }
    }
  }
  

  namespace inf112.skeleton.app {
    namespace network {
      abstract class inf112.skeleton.app.network.Network {
          + isHost : Boolean
          {static} + choseRole()
          {abstract} + initConnections()
          {abstract} + initialize()
          {static} + prompt()
          # registerClasses()
      }
    }
  }
  

  namespace inf112.skeleton.app {
    namespace network {
      class inf112.skeleton.app.network.NetworkClient {
          + client : Client
          # IP : String
          + initConnections()
          + initialize()
      }
    }
  }
  

  namespace inf112.skeleton.app {
    namespace network {
      class inf112.skeleton.app.network.NetworkData {
          {static} + classesToRegister()
      }
    }
  }
  

  namespace inf112.skeleton.app {
    namespace network {
      class inf112.skeleton.app.network.NetworkHost {
          + connections : Connection[]
          {static} + hostID : int
          + playerCards : HashMap<Integer, List<Card>>
          - server : Server
          + initConnections()
          + initialize()
          + promptCardDraw()
          + sendMapLayerWrapper()
          + sendWinner()
      }
    }
  }
  

  inf112.skeleton.app.network.NetworkClient -up-|> inf112.skeleton.app.network.Network
  inf112.skeleton.app.network.NetworkClient o-- inf112.skeleton.app.game.GameClient : gameClient
  inf112.skeleton.app.network.NetworkClient o-- inf112.skeleton.app.libgdx.Map : mlp
  inf112.skeleton.app.network.NetworkHost -up-|> inf112.skeleton.app.network.Network


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
