@startuml

title __OBJECTS's Class Diagram__\n

  namespace inf112.skeleton.app {
    namespace game {
      namespace objects {
        class inf112.skeleton.app.game.objects.Card {
            + Card()
            + getCardType()
            + setCardType()
        }
      }
    }
  }
  

  namespace inf112.skeleton.app {
    namespace game {
      namespace objects {
        enum CardType {
          BACK_UP
          FORWARDONE
          FORWARDTHREE
          FORWARDTWO
          TURNLEFT
          TURNRIGHT
          UTURN
        }
      }
    }
  }
  

  namespace inf112.skeleton.app {
    namespace game {
      namespace objects {
        class inf112.skeleton.app.game.objects.Flag {
            - position : GridPoint2
            + Flag()
            + Flag()
            + getX()
            + getY()
        }
      }
    }
  }
  

  namespace inf112.skeleton.app {
    namespace game {
      namespace objects {
        class inf112.skeleton.app.game.objects.PlayerToken {
            + ID : int
            + position : GridPoint2
            - flagsVisited : List<Flag>
            + getDirection()
            + getVisitedFlags()
            + getX()
            + getY()
            + move()
            + rotate()
            + visitFlag()
            + wouldEndUp()
            - moveDir()
        }
      }
    }
  }
  

  namespace inf112.skeleton.app {
    namespace game {
      namespace objects {
        enum CHARACTER_STATES {
          NONE
          PLAYERNORMAL
          PLAYERSELFNORMAL
          PLAYERSELFWON
          PLAYERWON
        }
      }
    }
  }
  

  namespace inf112.skeleton.app {
    namespace game {
      namespace objects {
        enum Direction {
          EAST
          NORTH
          SOUTH
          WEST
        }
      }
    }
  }
  

  inf112.skeleton.app.game.objects.Card o-- inf112.skeleton.app.game.objects.CardType : cardType
  inf112.skeleton.app.game.objects.PlayerToken o-- inf112.skeleton.app.game.objects.PlayerToken.CHARACTER_STATES : charState
  inf112.skeleton.app.game.objects.PlayerToken o-- inf112.skeleton.app.game.objects.PlayerToken.Direction : playerDirection
  inf112.skeleton.app.game.objects.PlayerToken +-down- inf112.skeleton.app.game.objects.PlayerToken.CHARACTER_STATES
  inf112.skeleton.app.game.objects.PlayerToken +-down- inf112.skeleton.app.game.objects.PlayerToken.Direction


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
